name = "LibTelnet"
uuid = "f9d8e1ac-e01e-48be-bfcb-6a787dcdbad6"
authors = ["envis10n"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
